# Generated by Django 3.0.8 on 2020-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('bigDescription', models.TextField()),
                ('smallDescription', models.CharField(blank=True, default='', max_length=100)),
                ('descFormation', models.TextField()),
                ('video', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('SimilarJob', models.ManyToManyField(related_name='_job_SimilarJob_+', to='core.Job')),
                ('profile', models.ManyToManyField(to='core.Profile')),
            ],
        ),
    ]
