# Generated by Django 3.1.4 on 2020-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201210_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='smallDescription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
