# Generated by Django 3.1.4 on 2020-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201209_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
